CREATE TABLE IF NOT EXISTS alcohol_type(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strength text NOT NULL
);

CREATE TABLE IF NOT EXISTS alcohol(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    alcohol_type bigint REFERENCES alcohol_type(id)
);

CREATE TABLE IF NOT EXISTS bar(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    address text NOT NULL
);

CREATE TABLE IF NOT EXISTS menu(
    bar_id bigint REFERENCES bar(id) ON DELETE CASCADE,
    alcohol_id bigint REFERENCES alcohol(id) ON DELETE CASCADE,
    PRIMARY KEY(bar_id,alcohol_id)
);